# 学习日记 20年03月10日

仔细深究了下throw的运行过程。

实际上是这样子的,假设 iterator是个gen()返回的迭代器对象
```
iterator.throw('error')

// 伪代码

在上一次停止的yield语句那, 把yield语句转换成 throw 'error'
然后执行到下一个yield语句 并返回右边的值

```

> iterator.throw() 不可以直接第一次使用，这相当于 在函数外 throw 。也很好理解，函数还没进行
> 你就给我throw() 当然是函数外部捕获的错误(这个函数外 指的是 gen函数外)

#### thunk

这个只能说，粗略的看了下。这个函数主要把一个多参数函数利用闭包转换成了单参数函数

```
//例如
fs.readFile(url , callback);

thunkify = function (fn) {
  return function (url) {
    // 获取args
    return function (callback) {
      return fn(url,callback)
    }
  }
}
```

我觉得有点像 函数柯里化啦！可能现在是时候，可以去尝试学习一下这一高阶技巧。